# Header
menu: #导航栏连接
  主页: /
  美食: /Food





rss: /atom.xml #rss地址  默认即可

#feed:
#  type: atom       #feed 类型 (atom/rss2)
#  path: /atom.xml   #rss 路径
#  limit: 20        #在 rss 中最多生成的文章数(0显示所有)


#icon http://fontawesome.io/
#首页显示
article_index:
  -  title: 欢迎
     content: 这里是大胖鱼和夏小咪的博客，欢迎光临！
     icon: icon-github-alt
  -  title: 探索生活的乐趣
     content: 我们努力在紧张的都市生活中寻找生活的乐趣!
     icon: icon-book
  -  title: 旅行
     content: 我们也喜欢到处走走看看，领略这个世界的美好！
     icon: icon-bolt
  -  title: 身在新加坡
     content: 新加坡是一个干净，高效，公平又友好的都市。我们享受在这里的每一天:)
     icon: icon-lab




# Content
excerpt_link: Read More  #阅读更多的文字显示
# fancybox: false  #开启fancybox效果 




# Miscellaneous #社交网络和统计连接地址
baidu_analytics: //hm.baidu.com/hm.js?fe2c7555911b8560db5e56121c5d5960 #百度统计
favicon: /css/favicon.ico
logo: /css/logo.png
